

module.exports.constants = {
  GATEWAY_DEVICE: '021b',
  '021b': 'GATEWAY_DEVICE',
  GATEWAY_ASK_DEVICE: '0206',
  CONFIRM_WRITE_DEVICE: '021f',
  '021f': 'CONFIRM_WRITE_DEVICE',
  CONFIRM_WRITE_TEMP_DEVICE: '0220',
  '0220': 'CONFIRM_WRITE_TEMP_DEVICE',
};
